# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: SAPDevOps

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    - task: CmdLine@2
            inputs:
              script: |
                IP=($(curl -s http://ipinfo.io/json | jq -r '.ip'))
                echo "##vso[task.setvariable variable=IP]$IP"

